feature_dist('cosTBTO', both=True, x_axis_lim=[0,1])
feature_dist('cosTBz', both=True, x_axis_lim=[0,1])
feature_dist('thrustBm', 'Thrust feature', both=True)
feature_dist('thrustOm', 'Thrust feature', both=True)
feature_dist('CleoConeCS__bo2__bc', 'Inner cone: 2', both=True)
feature_dist('CleoConeCS__bo6__bc', 'Middle cone: 6', both=True)
feature_dist('CleoConeCS__bo9__bc', 'Outer cone: 9', both=True)
feature_dist('foxWolframR1', both=True)
feature_dist('foxWolframR2', both=True)
feature_dist('foxWolframR3', both=True)
feature_dist('foxWolframR4', both=True)
feature_dist("R2", "2nd and 0th FW moment ratio", both=True)